version: '3.4'

services:
  db:
    image: postgres:14.2
    ports: 
      - 5432:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    env_file:
      - ./db/.env
    hostname: postgres
    restart: always

  chainlink:
    image: smartcontract/chainlink:1.8.1-root
    tty: true
    ports:
      - 6688:6688
    env_file:
      - ./chainlink/.env
    depends_on:
      - db
    command: local node
    restart: on-failure

  # adaptor:
  #   ports: 
  #     - 8080:8080
  #   build: ./adaptor
  #   image: adaptor
  #   restart: on-failure

volumes:
  database:
    driver: local
