version: '3.4'

services:
  db:
    image: postgres:14.2
    container_name: postgresql
    ports: 
      - 5432:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - database:/var/lib/postgresql/data
    env_file:
      - ./db/.env
    restart: always

  chainlink:
    image: smartcontract/chainlink:1.8.1-root
    tty: true
    ports:
      - 6688:6688
    env_file:
      - ./chainlink/.env
    depends_on:
      - db
    command: local node
    restart: on-failure

  adaptor:
    ports: 
      - 8082:3000
    build: ./adaptor
    image: adaptor
    restart: on-failure

volumes:
  database:
    driver: local
